#ifndef OM_LOG_H
#define OM_LOG_H

#define WORKTIPS_LOG_CATEGORY "worktips"

#define OMINFO  CLOG(INFO, WORKTIPS_LOG_CATEGORY)
#define OMWARN  CLOG(WARNING, WORKTIPS_LOG_CATEGORY)
#define OMERROR CLOG(ERROR, WORKTIPS_LOG_CATEGORY)

#define OMINFO_IF(cond)  CLOG_IF(cond, INFO, WORKTIPS_LOG_CATEGORY)
#define OMWARN_IF(cond)  CLOG_IF(cond, WARNING, WORKTIPS_LOG_CATEGORY)
#define OMERROR_IF(cond) CLOG_IF(cond, ERROR, WORKTIPS_LOG_CATEGORY)


#endif // OM_LOG_H
